// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// addCpp
double addCpp(NumericVector x);
RcppExport SEXP _calciSamantray_addCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(addCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// multiplyCpp
double multiplyCpp(NumericVector x);
RcppExport SEXP _calciSamantray_multiplyCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(multiplyCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// subtractCpp
double subtractCpp(double x, double y);
RcppExport SEXP _calciSamantray_subtractCpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(subtractCpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// divideCpp
double divideCpp(double x, double y);
RcppExport SEXP _calciSamantray_divideCpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(divideCpp(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_calciSamantray_addCpp", (DL_FUNC) &_calciSamantray_addCpp, 1},
    {"_calciSamantray_multiplyCpp", (DL_FUNC) &_calciSamantray_multiplyCpp, 1},
    {"_calciSamantray_subtractCpp", (DL_FUNC) &_calciSamantray_subtractCpp, 2},
    {"_calciSamantray_divideCpp", (DL_FUNC) &_calciSamantray_divideCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_calciSamantray(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
