# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addCpp <- function(x) {
    .Call(`_calciSamantray_addCpp`, x)
}

multiplyCpp <- function(x) {
    .Call(`_calciSamantray_multiplyCpp`, x)
}

subtractCpp <- function(x, y) {
    .Call(`_calciSamantray_subtractCpp`, x, y)
}

divideCpp <- function(x, y) {
    .Call(`_calciSamantray_divideCpp`, x, y)
}

